// Generated by flute sync. Edit recipes and components, not this registry.
import recipe0 from "./scenes/workspace-trail.scene.json";
export const sceneModules = {
  "src/flute/scenes/workspace-trail.scene.json": async () => ({default:recipe0}),
  "src/flute/scenes/workspace-trail.jsx": () => import("./scenes/workspace-trail"),
};
